services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=SchoolDatabase'
      - 'POSTGRES_PASSWORD=secret'
      - 'POSTGRES_USER=myuser'
    ports:
      - '5432'
    volumes:
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql
